
app:
    author: rhuertas
    grpcPort: 50053
    grpcAddress: "localhost"

spring:
  application:
    name: testapp
  data:
      mongodb:
        database: test
        uri: "mongodb://127.0.0.1:27017"

server:
    port: 8083

